### ISSUE TITLE
Server crashes on following error

### ISSUE THREAD

**Issue by eganbaatar** [eganbaatar/Poker#9]
ET /partials/table-6-handed.html 200 1ms - 6.15kb
GET /table-data/1 200 0ms - 609b
GET /lobby-data 200 2ms - 566b
GET /partials/table-2-handed.html 200 20ms - 5.04kb
GET /table-data/2 200 1ms - 620b
GET /lobby-data 304 0ms
GET /table-data/1 200 0ms - 873b
GET /lobby-data 304 0ms
events.js:287
      throw er; // Unhandled 'error' event
      ^

TypeError: Cannot read property 'public' of null
    at Table.playerLeft (/home/*/projects/Poker/poker_modules/table.js:732:31)
    at Socket.<anonymous> (/home/*/projects/Poker/app.js:166:23)
    at Socket.emit (events.js:310:20)
    at Socket.onevent (/home/*/projects/Poker/node_modules/socket.io/lib/socket.js:327:8)
    at Socket.socket.onevent (/home/*/projects/Poker/node_modules/express-socket.io-session/index.js:64:14)
    at Socket.onpacket (/home/*/projects/Poker/node_modules/socket.io/lib/socket.js:287:12)
    at Client.ondecoded (/home/*/projects/Poker/node_modules/socket.io/lib/client.js:193:14)
    at Decoder.Emitter.emit (/home/*/projects/Poker/node_modules/component-emitter/index.js:134:20)
    at Decoder.add (/home/*/projects/Poker/node_modules/socket.io-parser/index.js:247:12)
    at Client.ondata (/home/*/projects/Poker/node_modules/socket.io/lib/client.js:175:18)
Emitted 'error' event on Socket instance at:
    at Socket.emit (/home/*/projects/Poker/node_modules/socket.io/lib/socket.js:129:10)
    at Socket.onerror (/home/*/projects/Poker/node_modules/socket.io/lib/socket.js:390:8)
    at /home/*/projects/Poker/node_modules/socket.io/lib/client.js:209:12
    at Array.forEach (<anonymous>)
    at Client.onerror (/home/*/projects/Poker/node_modules/socket.io/lib/client.js:208:16)
    at Client.ondata (/home/*/projects/Poker/node_modules/socket.io/lib/client.js:177:10)
    at Socket.emit (events.js:310:20)
    at Socket.onPacket (/home/*/projects/Poker/node_modules/engine.io/lib/socket.js:99:14)
    at WebSocket.emit (events.js:310:20)
    at WebSocket.Transport.onPacket (/home/*/projects/Poker/node_modules/engine.io/lib/transport.js:91:8)

**Comment by eganbaatar** [comment]
Fixed temporarily by guarding nulls.
